20.QuadraticEquation/Square/Square/Controllers/DecisionController.cs
using Square.Logic.Models;
using Square.Logic.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Square.Controllers
{
    public class DecisionController : Controller
    {
        // GET: Decision
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Input model)
        {
            ICalculateService service = new CalculateService();

            service.Calculate(model);

            return View(model);
        }
    }
}

20.QuadraticEquation/Square/Square/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Square.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

20.QuadraticEquation/Square/Square/Views/Decision/Index.cshtml
@using Square.Logic.Models
@model Input

@{
    ViewBag.Title = "Index";
}

<h2>Quadratic Equation</h2>

@using (Html.BeginForm("Index", "Decision"))
{
    <table>
        <tr>
            <td>
                <b>
                    @Html.TextBoxFor(x => x.A, new { id = "A", maxlength = 10, size = 1 })x<sup><small>2</small></sup> +
                </b>
            </td>
            <td>
                <b>
                    @Html.TextBoxFor(x => x.B, new { id = "B", maxlength = 10, size = 1 })x +
                </b>
            </td>
            <td>
                <b>
                    @Html.TextBoxFor(x => x.C, new { id = "B", maxlength = 10, size = 1 }) = 0
                </b>
            </td>
        </tr>
        <tr>
            <td>A</td>
            <td>B</td>
            <td>C</td>
        </tr>
    </table>

    <br />
    <input type="submit" value="Find roots" />
}

    <div class="alert-info">
        <h3>Result</h3>
        @if (Model != null && Model.A != null)
        {
            if (Model.A == 0)
            {
                <p><b><font color="red">@Model.Notify</font></b></p>
            }
            else
            {
                if (Model.D < 0)
                {
                    <p><b><font color="blue">D = @Model.D</font></b></p>
                    <p><b><font color="blue">@Model.Notify</font></b></p>
                }

                if (Model.D == 0)
                {
                    <p><b><font color="blue">D = @Model.D</font></b></p>
                    <p><b><font color="blue">@Model.Notify</font></b></p>
                    <p><b><font color="blue">x1 = @Model.X.ElementAt(0)</font></b></p>
                }

                if (Model.D > 0)
                {
                    <p><b><font color="blue">D = @Model.D</font></b></p>
                    <p><b><font color="blue">@Model.Notify</font></b></p>
                    for (var i = 0; i < Model.X.Count; i++)
                    {
                        <p><b><font color="blue">x1 = @Model.X.ElementAt(i)</font></b></p>
                    }
                }
            }
        }
    </div>

20.QuadraticEquation/Square/Square/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

20.QuadraticEquation/Square/Square/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

20.QuadraticEquation/Square/Square/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

20.QuadraticEquation/Square/Square/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Decision", "Index", "Decision")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>